In [9]:
import numpy as np
import numpy.linalg as lin
import sympy as sp
import matplotlib.pyplot as plt
%matplotlib inline

# Notes

In [3]:
# 2 square brackets for a vector. Outer bracket is container for the whole vector/matrix, inner is the row
a = np.array([[1, 2, 3, 4, 5, 6]]) 

In [5]:
# Creating a matrix with np.reshape
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Alternative - creating it manually
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# Transpose
a.transpose()

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [8]:
# inverse of matrix
b = np.array([[1, 2, 3, 4]])
b = b.reshape(2, 2)
lin.inv(b)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [12]:
# rref: [1]: the rref form, [2]: list of indices for the pivot columns
sp.Matrix(b).rref()

(Matrix([
 [1.0,   0],
 [  0, 1.0]]), [0, 1])